// import type { Metadata } from "next";
// // import { GeistSans } from "geist/font/sans";
// // import { GeistMono } from "geist/font/mono"; // Removed due to missing module
// import "./globals.css";
// import { ThemeProvider } from "@/components/ThemeProvider";

// export const metadata: Metadata = {
//   title: "AI PDF Chatbot",
//   description: "Chat with your PDF documents using AI.",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         className="antialiased font-sans"
//       >
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="dark"
//           enableSystem
//           disableTransitionOnChange
//         >
//           <div className="fixed inset-0 -z-10 h-full w-full bg-white bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]">
//             <div className="fixed inset-0 -z-10 h-full w-full bg-black [mask-image:radial-gradient(ellipse_80%_50%_at_50%_0%,#000_70%,transparent_110%)]"></div>
//           </div>
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css' // <-- THIS LINE IS CRITICAL

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-900">
        {children}
      </body>
    </html>
  )
}